<?php

namespace JL\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjetImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetImageRepository extends EntityRepository
{
}
